### ISSUE TITLE
Error: <Shadow> is not a valid SSR component.

### ISSUE THREAD

**Issue by emmarvpol** [Schum123/svelte-loading-spinners#21]
Hello! Im getting the following error while I trying to use svelte-loading-spinners:

```
Error: <Shadow> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
    at Proxy.validate_component (/home/username/Documents/Svelte/node_modules/svelte/internal/index.js:1532:15)
    at eval (/src/components/Sidebar.svelte:45:59)
    at Object.$$render (/home/username/Documents/Svelte/node_modules/svelte/internal/index.js:1555:22)
    at eval (/home/username/Documents/Svelte/src/routes/__layout.svelte:33:87)
    at Object.$$render (/home/username/Documents/Svelte/node_modules/svelte/internal/index.js:1555:22)
    at root.svelte:36:44
    at $$render (/home/username/Documents/Svelte/node_modules/svelte/internal/index.js:1555:22)
    at Object.render (/home/username/Documents/Svelte/node_modules/svelte/internal/index.js:1563:26)
    at render_response (file:///home/username/Documents/Svelte/node_modules/@sveltejs/kit/dist/ssr.js:377:28)
    at runMicrotasks (<anonymous>)
```

**Comment by dbilgili** [comment]
Try to import it from the `src` folder of the package.

```js
import {Shadow} from 'svelte-loading-spinners/src'
```

**Comment by NordMagnus** [comment]
Importing from 'src' worked for me

**Comment by Schum123** [comment]
Should work without '/src' now.

https://svelte.dev/repl/5193e8564a3348fe8dec8d843468eeed?version=3.52.0
